"""Administrative CLI: ``oeop-admin <command>``.

Commands:
  seed-regions         Upsert the predefined region catalog (idempotent).
  seed-demo            Submit the demonstration analysis for real processing.
  requeue              Re-enqueue a failed or stuck analysis.
  queue-depth          Print the approximate queue depth.
  export-demo          Export a completed analysis as a portable demo bundle.
  import-demo          Import a demo bundle (metadata + preview artifacts).
"""

from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import sys
import uuid
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any

import anyio
from geoalchemy2.shape import from_shape
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from earth_observation.geometry import bbox_polygon, geodesic_area_km2, validate_bbox
from oeop_api.schemas import AnalysisCreateRequest
from oeop_api.services.analysis_service import create_analysis, get_demo_analysis_id
from oeop_core.azure.blob import BlobStore
from oeop_core.azure.queue import AnalysisQueue
from oeop_core.db.models import (
    Analysis,
    AnalysisStatus,
    Artifact,
    ArtifactType,
    Observation,
    Region,
    Scene,
    SceneSelectionStatus,
)
from oeop_core.db.session import create_engine, create_session_factory
from oeop_core.logging import configure_logging, get_logger
from oeop_core.regions import load_predefined_regions
from oeop_core.settings import Settings, get_settings

logger = get_logger(__name__)

#: Artifact types small enough (and licensed appropriately) to ship in a
#: portable demo bundle. COGs are regenerated by running a real analysis.
#: Processing generation in which the canonical analysis grid was introduced.
#: Anything older produced observations that are not comparable across dates.
GRID_MAJOR_VERSION = 2


def _major_version(version: str | None) -> int:
    """Major component of a processing version; unparseable values read as 0."""
    if not version:
        return 0
    try:
        return int(str(version).split(".", 1)[0])
    except ValueError:
        return 0


BUNDLED_ARTIFACT_TYPES = {
    ArtifactType.NDVI_PREVIEW,
    ArtifactType.TRUE_COLOR_PREVIEW,
    ArtifactType.SCENE_SUMMARY,
    ArtifactType.TIMESERIES_CSV,
    ArtifactType.ANALYSIS_SUMMARY,
    ArtifactType.PROVENANCE,
}


async def seed_regions(session: AsyncSession) -> int:
    count = 0
    for spec in load_predefined_regions():
        bbox = validate_bbox(spec["bbox"])
        polygon = bbox_polygon(bbox)
        area = geodesic_area_km2(polygon)
        existing = (
            await session.execute(select(Region).where(Region.slug == spec["slug"]))
        ).scalar_one_or_none()
        if existing is None:
            session.add(
                Region(
                    name=spec["name"],
                    slug=spec["slug"],
                    description=spec["description"],
                    geometry=from_shape(polygon, srid=4326),
                    bbox=list(bbox),
                    area_km2=area,
                    is_predefined=True,
                )
            )
        else:
            existing.name = spec["name"]
            existing.description = spec["description"]
            existing.bbox = list(bbox)
            existing.geometry = from_shape(polygon, srid=4326)
            existing.area_km2 = area
        count += 1
    await session.commit()
    logger.info("regions_seeded", count=count)
    return count


async def seed_demo(
    session: AsyncSession,
    queue: AnalysisQueue,
    settings: Settings,
    *,
    slug: str,
    start: date,
    end: date,
    cloud: float,
    scenes: int,
    if_missing: bool = False,
) -> uuid.UUID | None:
    """Submit the demonstration analysis.

    With ``if_missing`` the command is idempotent and safe to run on every
    deployment: it does nothing when a demo analysis already exists in a
    usable state, so the landing page always has something to link to without
    paying for a reprocess on each deploy.
    """
    if if_missing:
        existing = (
            await session.execute(
                select(Analysis)
                .where(
                    Analysis.is_demo.is_(True),
                    Analysis.status.in_(
                        [
                            AnalysisStatus.SUCCEEDED,
                            AnalysisStatus.QUEUED,
                            AnalysisStatus.RUNNING,
                        ]
                    ),
                    # Only a current-generation demo counts; a legacy one would
                    # showcase pre-canonical-grid results.
                    Analysis.grid.is_not(None),
                )
                .order_by(Analysis.submitted_at.desc())
                .limit(1)
            )
        ).scalar_one_or_none()
        if existing is not None:
            logger.info(
                "demo_analysis_present",
                analysis_id=str(existing.id),
                status=existing.status.value,
            )
            print(existing.id)
            return existing.id

    region = (await session.execute(select(Region).where(Region.slug == slug))).scalar_one_or_none()
    if region is None:
        raise SystemExit(f"Region '{slug}' not found; run seed-regions first")
    analysis = await create_analysis(
        session=session,
        queue=queue,
        settings=settings,
        request=AnalysisCreateRequest(
            region_id=region.id,
            start_date=start,
            end_date=end,
            max_cloud_cover_pct=cloud,
            scene_limit=scenes,
        ),
        is_demo=True,
    )
    logger.info("demo_analysis_submitted", analysis_id=str(analysis.id))
    print(analysis.id)
    return analysis.id


async def delete_analyses(
    session: AsyncSession,
    blob: BlobStore,
    *,
    analysis_ids: list[uuid.UUID] | None = None,
    legacy: bool = False,
    dry_run: bool = False,
    force: bool = False,
) -> int:
    """Permanently delete analyses and their stored artifacts.

    Blobs are deleted BEFORE the database rows. That ordering matters: if the
    run is interrupted, rows pointing at missing blobs are visible and
    recoverable, whereas deleting rows first would leave orphaned blobs that
    nothing references and nobody notices (they would keep costing money until
    the lifecycle policy expired them).

    ``legacy`` targets analyses from a processing generation older than the
    canonical grid (major version < 2); those cannot be compared across dates
    when the AOI crossed a Sentinel-2 tile boundary.

    The filter deliberately keys on ``processing_version``, NOT on
    ``grid IS NULL``: an analysis that is still queued has no grid yet either,
    and sweeping those up would delete work in flight.
    """
    if legacy:
        result = await session.execute(select(Analysis).order_by(Analysis.submitted_at))
        targets = [
            a for a in result.scalars() if _major_version(a.processing_version) < GRID_MAJOR_VERSION
        ]
    elif analysis_ids:
        targets = []
        for analysis_id in analysis_ids:
            analysis = await session.get(Analysis, analysis_id)
            if analysis is None:
                raise SystemExit(f"Analysis {analysis_id} not found")
            targets.append(analysis)
    else:
        raise SystemExit("Provide --analysis-id or --legacy")

    if not targets:
        print("No matching analyses; nothing to delete.")
        return 0

    # Never remove work that is still in flight; a queued or running analysis
    # is not a stale record, and deleting it would strand a queue message.
    in_flight = [a for a in targets if a.status in (AnalysisStatus.QUEUED, AnalysisStatus.RUNNING)]
    if in_flight and not force:
        raise SystemExit(
            f"Refusing to delete {len(in_flight)} analyses that are still "
            f"{'/'.join(sorted({a.status.value for a in in_flight}))}. "
            "Wait for them to finish, or re-run with --force."
        )

    # Refuse to remove the analysis the landing page currently advertises,
    # unless explicitly forced — deleting it would leave a dead demo link.
    demo_id = await get_demo_analysis_id(session)
    protected = [a for a in targets if a.id == demo_id]
    if protected and not force:
        raise SystemExit(
            f"Refusing to delete {protected[0].id}: it is the demonstration "
            "analysis the public landing page links to. Re-run with --force if "
            "you really mean it, after seeding a replacement."
        )

    total_blobs = 0
    for analysis in targets:
        prefix = analysis.output_prefix or f"analyses/{analysis.id}"
        artifacts = (
            (await session.execute(select(Artifact).where(Artifact.analysis_id == analysis.id)))
            .scalars()
            .all()
        )
        size_mb = sum(a.size_bytes for a in artifacts) / 1e6
        label = (
            f"{analysis.id}  v{analysis.processing_version}  "
            f"{analysis.status.value}  {len(artifacts)} artifacts  {size_mb:.1f} MB"
        )
        if dry_run:
            print(f"  [dry-run] would delete {label}")
            continue

        deleted = blob.delete_prefix(prefix.rstrip("/") + "/")
        total_blobs += deleted
        await session.delete(analysis)  # cascades to scenes/observations/artifacts
        await session.commit()
        logger.info(
            "analysis_deleted",
            analysis_id=str(analysis.id),
            processing_version=analysis.processing_version,
            blobs_deleted=deleted,
        )
        print(f"  deleted {label}  ({deleted} blobs removed)")

    if dry_run:
        print(f"dry run: {len(targets)} analyses would be deleted (nothing changed)")
        return 0
    print(f"deleted {len(targets)} analyses and {total_blobs} blobs")
    return len(targets)


async def requeue(session: AsyncSession, queue: AnalysisQueue, analysis_id: uuid.UUID) -> None:
    analysis = await session.get(Analysis, analysis_id)
    if analysis is None:
        raise SystemExit(f"Analysis {analysis_id} not found")
    stale_cutoff = datetime.now(UTC) - timedelta(hours=2)
    if analysis.status == AnalysisStatus.RUNNING and (
        analysis.started_at is None or analysis.started_at > stale_cutoff
    ):
        raise SystemExit(
            "Analysis appears to be actively running; refusing to requeue. "
            "Wait for it to finish or become stale (>2h)."
        )
    if analysis.status == AnalysisStatus.SUCCEEDED:
        raise SystemExit("Analysis already succeeded; nothing to requeue.")
    analysis.status = AnalysisStatus.QUEUED
    analysis.status_message = "Requeued by operator"
    analysis.failure_category = None
    analysis.failure_detail = None
    analysis.retry_count += 1
    await session.commit()
    await anyio.to_thread.run_sync(queue.send_analysis, str(analysis_id))
    logger.info("analysis_requeued", analysis_id=str(analysis_id))
    print(f"requeued {analysis_id}")


def _record(obj: Any, fields: list[str]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for field in fields:
        value = getattr(obj, field)
        if isinstance(value, uuid.UUID):
            value = str(value)
        elif isinstance(value, datetime | date):
            value = value.isoformat()
        elif hasattr(value, "value") and not isinstance(value, int | float | str):
            value = value.value
        out[field] = value
    return out


ANALYSIS_FIELDS = [
    "id",
    "region_id",
    "bbox",
    "area_km2",
    "start_date",
    "end_date",
    "collection",
    "max_cloud_cover_pct",
    "scene_limit",
    "operation",
    "processing_config",
    "grid",
    "processing_version",
    "git_commit_sha",
    "status",
    "status_message",
    "submitted_at",
    "started_at",
    "completed_at",
    "retry_count",
    "output_prefix",
    "summary",
    "is_demo",
]
SCENE_FIELDS = [
    "id",
    "analysis_id",
    "stac_collection",
    "stac_item_id",
    "acquisition_key",
    "contributing_item_ids",
    "tile_ids",
    "granule_count",
    "aoi_coverage_pct",
    "valid_pixel_pct",
    "observed_at",
    "bbox",
    "cloud_cover_pct",
    "source_provider",
    "platform",
    "instruments",
    "assets",
    "selection_status",
    "exclusion_reason",
    "quality",
]
OBSERVATION_FIELDS = [
    "id",
    "analysis_id",
    "scene_id",
    "ndvi_min",
    "ndvi_max",
    "ndvi_mean",
    "ndvi_median",
    "ndvi_std",
    "ndvi_p10",
    "ndvi_p25",
    "ndvi_p75",
    "ndvi_p90",
    "valid_pixel_count",
    "masked_pixel_count",
    "aoi_pixel_count",
    "valid_pixel_pct",
    "zero_denominator_pixel_count",
    "uncovered_pixel_count",
    "aoi_coverage_pct",
    "valid_coverage_pct",
    "missing_data_pct",
    "granule_count",
    "mask_scl_classes",
    "band_scaling",
    "processing_params",
    "processing_seconds",
]
ARTIFACT_FIELDS = [
    "id",
    "analysis_id",
    "scene_id",
    "artifact_type",
    "container",
    "blob_path",
    "content_type",
    "size_bytes",
    "sha256",
    "crs",
    "bbox",
    "provenance",
]


async def export_demo(
    session: AsyncSession, blob: BlobStore, analysis_id: uuid.UUID, out_dir: Path
) -> None:
    analysis = await session.get(Analysis, analysis_id)
    if analysis is None or analysis.status != AnalysisStatus.SUCCEEDED:
        raise SystemExit("Analysis not found or not succeeded")
    region_slug = None
    if analysis.region_id:
        region = await session.get(Region, analysis.region_id)
        region_slug = region.slug if region else None
    scenes = (
        (await session.execute(select(Scene).where(Scene.analysis_id == analysis_id)))
        .scalars()
        .all()
    )
    observations = (
        (await session.execute(select(Observation).where(Observation.analysis_id == analysis_id)))
        .scalars()
        .all()
    )
    artifacts = (
        (await session.execute(select(Artifact).where(Artifact.analysis_id == analysis_id)))
        .scalars()
        .all()
    )

    if out_dir.exists():
        shutil.rmtree(out_dir)
    blob_dir = out_dir / "blobs"
    blob_dir.mkdir(parents=True)

    bundled: list[dict[str, Any]] = []
    for artifact in artifacts:
        if artifact.artifact_type not in BUNDLED_ARTIFACT_TYPES:
            continue
        data = await anyio.to_thread.run_sync(blob.download_bytes, artifact.blob_path)
        local_name = artifact.blob_path.replace("/", "__")
        (blob_dir / local_name).write_bytes(data)
        record = _record(artifact, ARTIFACT_FIELDS)
        record["file"] = f"blobs/{local_name}"
        bundled.append(record)

    manifest = {
        "format_version": "1.0",
        "attribution": (
            "Derived previews and statistics from Copernicus Sentinel-2 data "
            "(ESA), accessed via Microsoft Planetary Computer. Sentinel data is "
            "provided under the Legal Notice on the use of Copernicus Sentinel "
            "Data and Service Information."
        ),
        "region_slug": region_slug,
        "analysis": _record(analysis, ANALYSIS_FIELDS),
        "scenes": [_record(s, SCENE_FIELDS) for s in scenes],
        "observations": [_record(o, OBSERVATION_FIELDS) for o in observations],
        "artifacts": bundled,
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"exported demo bundle to {out_dir} ({len(bundled)} artifacts)")


async def import_demo(session: AsyncSession, blob: BlobStore, bundle_dir: Path) -> uuid.UUID:
    manifest = json.loads((bundle_dir / "manifest.json").read_text())
    a = manifest["analysis"]
    analysis_id = uuid.UUID(a["id"])
    existing = await session.get(Analysis, analysis_id)
    if existing is not None:
        print(f"demo analysis {analysis_id} already imported")
        return analysis_id

    region_id = None
    if manifest.get("region_slug"):
        region = (
            await session.execute(select(Region).where(Region.slug == manifest["region_slug"]))
        ).scalar_one_or_none()
        region_id = region.id if region else None

    def parse_dt(value: str | None) -> datetime | None:
        return datetime.fromisoformat(value) if value else None

    session.add(
        Analysis(
            id=analysis_id,
            region_id=region_id,
            geometry=from_shape(bbox_polygon(tuple(a["bbox"])), srid=4326)
            if region_id is None
            else None,
            bbox=a["bbox"],
            area_km2=a["area_km2"],
            start_date=date.fromisoformat(a["start_date"]),
            end_date=date.fromisoformat(a["end_date"]),
            collection=a["collection"],
            max_cloud_cover_pct=a["max_cloud_cover_pct"],
            scene_limit=a["scene_limit"],
            operation=a["operation"],
            processing_config=a["processing_config"],
            grid=a.get("grid"),
            processing_version=a["processing_version"],
            git_commit_sha=a.get("git_commit_sha"),
            status=AnalysisStatus(a["status"]),
            status_message="Imported precomputed demonstration analysis",
            submitted_at=parse_dt(a["submitted_at"]) or datetime.now(UTC),
            started_at=parse_dt(a.get("started_at")),
            completed_at=parse_dt(a.get("completed_at")),
            retry_count=a.get("retry_count", 0),
            output_prefix=a.get("output_prefix"),
            summary=a.get("summary"),
            is_demo=True,
        )
    )
    for s in manifest["scenes"]:
        session.add(
            Scene(
                id=uuid.UUID(s["id"]),
                analysis_id=analysis_id,
                stac_collection=s["stac_collection"],
                stac_item_id=s["stac_item_id"],
                acquisition_key=s.get("acquisition_key"),
                contributing_item_ids=s.get("contributing_item_ids"),
                tile_ids=s.get("tile_ids"),
                granule_count=s.get("granule_count") or 1,
                aoi_coverage_pct=s.get("aoi_coverage_pct"),
                valid_pixel_pct=s.get("valid_pixel_pct"),
                observed_at=datetime.fromisoformat(s["observed_at"]),
                bbox=s.get("bbox"),
                cloud_cover_pct=s.get("cloud_cover_pct"),
                source_provider=s["source_provider"],
                platform=s.get("platform"),
                instruments=s.get("instruments"),
                assets=s["assets"],
                selection_status=SceneSelectionStatus(s["selection_status"]),
                exclusion_reason=s.get("exclusion_reason"),
                quality=s.get("quality"),
            )
        )
    for o in manifest["observations"]:
        values = {k: o[k] for k in OBSERVATION_FIELDS}
        values["id"] = uuid.UUID(values["id"])
        values["analysis_id"] = uuid.UUID(values["analysis_id"])
        values["scene_id"] = uuid.UUID(values["scene_id"])
        session.add(Observation(**values))
    for art in manifest["artifacts"]:
        data = (bundle_dir / art["file"]).read_bytes()
        local_tmp = bundle_dir / "._upload.tmp"
        local_tmp.write_bytes(data)
        await anyio.to_thread.run_sync(
            blob.upload_file, local_tmp, art["blob_path"], art["content_type"]
        )
        local_tmp.unlink()
        session.add(
            Artifact(
                id=uuid.UUID(art["id"]),
                analysis_id=analysis_id,
                scene_id=uuid.UUID(art["scene_id"]) if art.get("scene_id") else None,
                artifact_type=ArtifactType(art["artifact_type"]),
                container=art["container"],
                blob_path=art["blob_path"],
                content_type=art["content_type"],
                size_bytes=art["size_bytes"],
                sha256=art["sha256"],
                crs=art.get("crs"),
                bbox=art.get("bbox"),
                provenance=art.get("provenance"),
            )
        )
    await session.commit()
    print(f"imported demo analysis {analysis_id}")
    return analysis_id


async def _run(args: argparse.Namespace) -> None:
    settings = get_settings()
    configure_logging(settings.log_level, service="oeop-admin")
    engine = create_engine(settings)
    factory: async_sessionmaker[AsyncSession] = create_session_factory(engine)
    try:
        if args.command == "seed-regions":
            async with factory() as session:
                await seed_regions(session)
        elif args.command == "seed-demo":
            queue = AnalysisQueue(settings)
            queue.ensure_queues()
            BlobStore(settings).ensure_container()
            async with factory() as session:
                await seed_demo(
                    session,
                    queue,
                    settings,
                    slug=args.slug,
                    start=date.fromisoformat(args.start),
                    end=date.fromisoformat(args.end),
                    cloud=args.cloud,
                    scenes=args.scenes,
                    if_missing=args.if_missing,
                )
        elif args.command == "requeue":
            queue = AnalysisQueue(settings)
            async with factory() as session:
                await requeue(session, queue, uuid.UUID(args.analysis_id))
        elif args.command == "delete-analysis":
            blob = BlobStore(settings)
            async with factory() as session:
                await delete_analyses(
                    session,
                    blob,
                    analysis_ids=[uuid.UUID(a) for a in (args.analysis_id or [])],
                    legacy=args.legacy,
                    dry_run=args.dry_run,
                    force=args.force,
                )
        elif args.command == "queue-depth":
            queue = AnalysisQueue(settings)
            print(queue.approximate_depth())
        elif args.command == "export-demo":
            blob = BlobStore(settings)
            async with factory() as session:
                await export_demo(session, blob, uuid.UUID(args.analysis_id), Path(args.out))
        elif args.command == "import-demo":
            blob = BlobStore(settings)
            blob.ensure_container()
            async with factory() as session:
                await import_demo(session, blob, Path(args.bundle))
        else:  # pragma: no cover - argparse enforces choices
            raise SystemExit(f"Unknown command {args.command}")
    finally:
        await engine.dispose()


def main() -> None:
    parser = argparse.ArgumentParser(prog="oeop-admin", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("seed-regions", help="Upsert predefined regions")

    demo = sub.add_parser("seed-demo", help="Submit the demonstration analysis")
    demo.add_argument("--slug", default="southeast-michigan-demo")
    demo.add_argument("--start", default="2024-04-01")
    demo.add_argument("--end", default="2024-10-31")
    demo.add_argument("--cloud", type=float, default=30.0)
    demo.add_argument("--scenes", type=int, default=6)
    demo.add_argument(
        "--if-missing",
        action="store_true",
        help="Do nothing if a current-generation demo analysis already exists "
        "(idempotent; safe to run on every deployment)",
    )

    rq = sub.add_parser("requeue", help="Requeue a failed/stuck analysis")
    rq.add_argument("--analysis-id", required=True)

    dele = sub.add_parser(
        "delete-analysis",
        help="Permanently delete analyses and their stored artifacts",
    )
    dele.add_argument(
        "--analysis-id",
        action="append",
        help="Analysis to delete; repeat for several",
    )
    dele.add_argument(
        "--legacy",
        action="store_true",
        help="Delete every analysis processed before the canonical grid (grid IS NULL)",
    )
    dele.add_argument(
        "--dry-run", action="store_true", help="List what would be deleted, change nothing"
    )
    dele.add_argument(
        "--force",
        action="store_true",
        help="Allow deleting the analysis the landing page currently links to",
    )

    sub.add_parser("queue-depth", help="Print approximate queue depth")

    exp = sub.add_parser("export-demo", help="Export a demo bundle")
    exp.add_argument("--analysis-id", required=True)
    exp.add_argument("--out", default="data/demo/southeast-michigan")

    imp = sub.add_parser("import-demo", help="Import a demo bundle")
    imp.add_argument("--bundle", default="data/demo/southeast-michigan")

    args = parser.parse_args()
    try:
        asyncio.run(_run(args))
    except KeyboardInterrupt:
        sys.exit(130)


if __name__ == "__main__":
    main()
