# type: ignore
"""selection strategy and seasonal target

Revision ID: 0f86dccd982a
Revises: 3e21c39711b2
Create Date: 2026-08-05 15:06:30.278266+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0f86dccd982a"
down_revision: str | None = "3e21c39711b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # selection_strategy carries a server default so this applies to databases
    # holding analyses that predate the seasonal strategy; those were all
    # selected by the evenly-spread temporal algorithm.
    op.add_column(
        "analyses",
        sa.Column(
            "selection_strategy",
            sa.String(length=20),
            nullable=False,
            server_default=sa.text("'temporal'"),
            comment="temporal = evenly spread; seasonal = one per year at the same season",
        ),
    )
    op.add_column("analyses", sa.Column("seasonal_target_month", sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "seasonal_target_month")
    op.drop_column("analyses", "selection_strategy")
