# type: ignore
"""canonical analysis grid and acquisition coverage

Revision ID: 3e21c39711b2
Revises: 8b1830f1b7fc
Create Date: 2026-08-03 16:26:03.252342+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "3e21c39711b2"
down_revision: str | None = "8b1830f1b7fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Non-nullable additions carry server defaults so the migration applies to
    # databases that already hold analyses from processing version 1.x. Rows
    # written before the canonical grid existed keep grid=NULL, and the API
    # reports them as legacy (their observations are NOT comparable across
    # dates when the AOI crossed a Sentinel-2 tile boundary).
    op.add_column(
        "analyses",
        sa.Column(
            "grid",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="Canonical analysis grid every observation is aligned to",
        ),
    )
    op.add_column(
        "observations",
        sa.Column(
            "uncovered_pixel_count", sa.BigInteger(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "observations",
        sa.Column("aoi_coverage_pct", sa.Float(), nullable=False, server_default=sa.text("100.0")),
    )
    op.add_column(
        "observations",
        sa.Column("valid_coverage_pct", sa.Float(), nullable=False, server_default=sa.text("0.0")),
    )
    op.add_column(
        "observations",
        sa.Column("missing_data_pct", sa.Float(), nullable=False, server_default=sa.text("0.0")),
    )
    op.add_column(
        "observations",
        sa.Column("granule_count", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    op.add_column(
        "scenes",
        sa.Column(
            "acquisition_key",
            sa.String(length=200),
            nullable=True,
            comment="Deterministic key grouping granules of one acquisition",
        ),
    )
    op.add_column(
        "scenes",
        sa.Column(
            "contributing_item_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="Every STAC item mosaicked for this observation",
        ),
    )
    op.add_column(
        "scenes",
        sa.Column(
            "tile_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
            comment="Sentinel-2 MGRS tiles contributing",
        ),
    )
    op.add_column(
        "scenes",
        sa.Column("granule_count", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    op.add_column("scenes", sa.Column("aoi_coverage_pct", sa.Float(), nullable=True))
    op.add_column("scenes", sa.Column("valid_pixel_pct", sa.Float(), nullable=True))
    op.alter_column(
        "scenes",
        "stac_item_id",
        existing_type=sa.VARCHAR(length=120),
        comment="Primary/representative granule of the acquisition",
        existing_nullable=False,
    )
    op.alter_column(
        "scenes",
        "observed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Acquisition (sensing) time, not processing time",
        existing_nullable=False,
    )
    op.alter_column(
        "scenes",
        "assets",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Original unsigned asset hrefs, keyed by contributing item id then role",
        existing_comment="Original unsigned asset hrefs by role",
        existing_nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scenes",
        "assets",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Original unsigned asset hrefs by role",
        existing_comment="Original unsigned asset hrefs, keyed by contributing item id then role",
        existing_nullable=False,
    )
    op.alter_column(
        "scenes",
        "observed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Acquisition (sensing) time, not processing time",
        existing_nullable=False,
    )
    op.alter_column(
        "scenes",
        "stac_item_id",
        existing_type=sa.VARCHAR(length=120),
        comment=None,
        existing_comment="Primary/representative granule of the acquisition",
        existing_nullable=False,
    )
    op.drop_column("scenes", "valid_pixel_pct")
    op.drop_column("scenes", "aoi_coverage_pct")
    op.drop_column("scenes", "granule_count")
    op.drop_column("scenes", "tile_ids")
    op.drop_column("scenes", "contributing_item_ids")
    op.drop_column("scenes", "acquisition_key")
    op.drop_column("observations", "granule_count")
    op.drop_column("observations", "missing_data_pct")
    op.drop_column("observations", "valid_coverage_pct")
    op.drop_column("observations", "aoi_coverage_pct")
    op.drop_column("observations", "uncovered_pixel_count")
    op.drop_column("analyses", "grid")
