# type: ignore
"""region grouping

Revision ID: ae9c0e93a493
Revises: 0f86dccd982a
Create Date: 2026-08-05 18:01:03.824779+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "ae9c0e93a493"
down_revision: str | None = "0f86dccd982a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Server default so the column applies to databases that already hold the
    # original Michigan-only catalog; `seed-regions` then sets the real group.
    op.add_column(
        "regions",
        sa.Column(
            "region_group",
            sa.String(length=40),
            nullable=False,
            server_default=sa.text("'Global'"),
            comment="Grouping shown in the UI, e.g. Michigan or Global",
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "region_group")
